// Interop tests against a REAL OpenSSH sshd (not the node test double).
// Skipped unless sshd is listening on 127.0.0.1:2222 with user "mobatest".
// See TestSupport/README-interop.md for the one-time local setup.

import Foundation
import XCTest

@testable import MacMobaCore

final class OpenSSHInteropTests: XCTestCase {
    static let host = "127.0.0.1"
    static let port = 2222
    static let keyPath = "/tmp/test_ed25519"

    private func sshdAvailable() -> Bool {
        #if canImport(Darwin)
        let sock = socket(AF_INET, SOCK_STREAM, 0)
        #else
        let sock = socket(AF_INET, Int32(SOCK_STREAM.rawValue), 0)
        #endif
        defer { close(sock) }
        var addr = sockaddr_in()
        addr.sin_family = sa_family_t(AF_INET)
        addr.sin_port = UInt16(Self.port).bigEndian
        inet_pton(AF_INET, Self.host, &addr.sin_addr)
        let r = withUnsafePointer(to: &addr) {
            $0.withMemoryRebound(to: sockaddr.self, capacity: 1) {
                connect(sock, $0, socklen_t(MemoryLayout<sockaddr_in>.size))
            }
        }
        return r == 0
    }

    final class Collector: @unchecked Sendable {
        private let lock = NSLock()
        private var buffer = Data()
        func append(_ d: Data) { lock.lock(); buffer.append(d); lock.unlock() }
        var text: String { lock.lock(); defer { lock.unlock() }; return String(decoding: buffer, as: UTF8.self) }
    }

    private func waitUntil(_ timeout: TimeInterval, _ cond: () -> Bool) {
        let deadline = Date().addingTimeInterval(timeout)
        while Date() < deadline {
            if cond() { return }
            Thread.sleep(forTimeInterval: 0.05)
        }
    }

    /// Password auth + run a real command in a real bash over a real PTY.
    func testPasswordAuthRealShell() async throws {
        try XCTSkipUnless(sshdAvailable(), "no sshd on \(Self.host):\(Self.port)")
        let collector = Collector()
        let conn = try await SSHConnection.connect(
            config: SessionConfig(name: "real", host: Self.host, port: Self.port,
                                  username: "mobatest", authType: "password", password: "testpw123"),
            onData: { collector.append($0) },
            onExit: { _ in }
        )
        defer { conn.close() }

        conn.write(Data("echo interop-$((6*7))\n".utf8))
        waitUntil(5) { collector.text.contains("interop-42") }
        XCTAssertTrue(collector.text.contains("interop-42"), "output: \(collector.text.suffix(300))")
    }

    /// ed25519 keyfile auth end-to-end: exercises OpenSSHKeyParser against a
    /// key generated by real ssh-keygen, and publickey auth against real sshd.
    func testEd25519KeyfileAuth() async throws {
        try XCTSkipUnless(sshdAvailable(), "no sshd on \(Self.host):\(Self.port)")
        try XCTSkipUnless(FileManager.default.fileExists(atPath: Self.keyPath),
                          "no test key at \(Self.keyPath)")
        let collector = Collector()
        let conn = try await SSHConnection.connect(
            config: SessionConfig(name: "real-key", host: Self.host, port: Self.port,
                                  username: "mobatest", authType: "keyfile", keyPath: Self.keyPath),
            onData: { collector.append($0) },
            onExit: { _ in }
        )
        defer { conn.close() }

        conn.write(Data("whoami\n".utf8))
        waitUntil(5) { collector.text.contains("mobatest") }
        XCTAssertTrue(collector.text.contains("mobatest"), "output: \(collector.text.suffix(300))")
    }

    /// Resize must reach the real PTY: stty should report the new size.
    func testWindowChangePropagates() async throws {
        try XCTSkipUnless(sshdAvailable(), "no sshd on \(Self.host):\(Self.port)")
        let collector = Collector()
        let conn = try await SSHConnection.connect(
            config: SessionConfig(name: "real", host: Self.host, port: Self.port,
                                  username: "mobatest", authType: "password", password: "testpw123"),
            cols: 80, rows: 24,
            onData: { collector.append($0) },
            onExit: { _ in }
        )
        defer { conn.close() }

        conn.resize(cols: 133, rows: 47)
        Thread.sleep(forTimeInterval: 0.3)
        conn.write(Data("stty size\n".utf8))
        waitUntil(5) { collector.text.contains("47 133") }
        XCTAssertTrue(collector.text.contains("47 133"), "output: \(collector.text.suffix(300))")
    }
}
